<h3> <?php echo $red->post_title?> </h3>
<p> <?php echo $red->post_date?> </p>
<p> <?php echo $red->post_content?> </p>
<img src="<?php echo $putanjaslike ?>"  alt="<?php echo $red->image?>" width="400" height="341">






<br>


<a href="/eating/promjena?post_id=<?php echo $red->post_id?>"><i title="Promjeni" ></i> Change</a> 


<a onclick="return confirm('Sigurno zelis obrisati <?php echo $red->post_title ?> ');" 
    href="/eating/obrisi?post_id=<?php echo $red->post_id ?>">
    <i title="Ukloni"></i>Delete</a>
