
<lang="en">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="bmi/bootstrap.min.css">
	<head>
	<section class="jumbotron text-center">
	<body class="container">
		<h1>Body Mass Index Calculator</h1>
		<p>Please enter your weight and height details below to discover your body mass index measurement.</p>
		</section>
		<div  section class="jumbotron text-center">
			<form action="rezultat" method="post">
				<div class="col-md-3">
					Weight (kg): <input type="text" name="weight">
				</div>
				<div class="col-md-3">
					Height (meters): <input type="text" name="height">
				</div>
				
				<div class="col-md-3"> 
					<input type="submit" value="Submit">
				</div>
			</form>
		</div><!--end row-->
	</body>
