<section class="jumbotron text-center">
<div class="w3-container w3-grey">
 
          <h1 class="display-4">Fitness talks</h1>
          <img  class="container"  src="<?php echo App::config('url')?>public/slike/main.png" rel="stylesheet">


          <p class="lead text-muted">No pain, no gain. Shut up and train.</p>
          <p>
          <a href="/index/onama" class="btn btn-primary my-2">ER DIAGRAM </a>  
            
          </p>
        </div>
        </section>
        <div class="album py-5 bg-light">
    
        <div class="container">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" img src=" <?php echo App::config('url')?>public/slike/workouts1.png" rel="stylesheet">
                <div class="card-body">
                  <p class="card-text">Tell us, show or find the best workout routines and training plans for you to do at home or in the gym. Show your workout progress and motivate others.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">

                    <a href="/workouts/index">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View&Edit</button>
                     
                      </a>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
        

    
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
              <img class="card-img-top" img src=" <?php echo App::config('url')?>public/slike/healthyeating.png" rel="stylesheet">
                <div class="card-body">
                  <p class="card-text">Tell us, show or learn how to eat healthy food and meals. Here is all about recipes, videos, diet tips, eating plans and nutrition advice.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">

                    <a href="/eating/index">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View&Edit</button>
                    
                      </a>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
              <img class="card-img-top" img src=" <?php echo App::config('url')?>public/slike/equip.png" rel="stylesheet">
                <div class="card-body">
                  <p class="card-text">Tell us all about Gym Source’s equipment, including ellipticals, exercise bikes, free weights, home gyms, indoor cycles, rowers, steppers, treadmills and more. </p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    <a href="/equipment/index">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View&Edit</button>
                 
                      </a>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
