<section class="jumbotron text-center">
<div class="container">
          <h3 class="display-4">Welcome <?php echo $_SESSION['operater']->ime . 
                ' ' . $_SESSION['operater']->prezime; ?>
            
          </h3>

    
          
            <svg xmlns="http://www.w3.org/2000/svg" class="icon-share icon-share-email-outline" width="44" height="44" viewBox="0 0 24 24" role="img" aria-hidden="true" tabindex="-1"><path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 14H4V8l8 5 8-5v10zm-8-7L4 6h16l-8 5z" fill-opacity=".65"></path>
          
          
          </svg></span>
          
        </a>
      </div>
    </div>
  </div>

  


          

  <i class="fas fa-user"><a href="#" class="menu-link expand-trigger" data-tracking-label="your account" aria-expanded="false">
                              <!-- This is for auth partial core has empty partial override the content in brands -->
                              <span class="secondary-menu-label">Your Account</span>          <span class="icon desktop-only"><span class="icon icon-down-triangle utility-icon color-gray-6 ">
                      
                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="8" viewBox="0 0 255 255" role="img" aria-hidden="true" tabindex="-1"><title>Down Triangle</title><path d="M0 63.75l127.5 127.5L255 63.75z"></path></svg>
                      
                      
                      </span>
                      </span>
                                <span class="icon accordion-arrow mobile-only"><span class="icon icon-down utility-icon ">
                      
                        
                      
                      </span>
                      </span>
                      </i>
<br>



<button type="button" class="btn btn-default" a href="/index/prijava"><?php if(!isset($_SESSION['operater'])): ?> Sing up</a><?php else:?>
                <a href="/index/odjava">Odjavi 
                <?php echo $_SESSION['operater']->ime . 
                ' ' . $_SESSION['operater']->prezime; ?></a>
            <?php endif;?></button>