<form class="log-in-form" method="POST"
action="/workouts/promjena">
 
  
<label>Title
    <input type="text" id="post_title" name="post_title" value="<?php 
    echo $workouts->post_title;
    ?>">
  </label>
  
  <label>Content
    <input type="text" id="post_content" name="post_content" 
    value="<?php 
    echo $workouts->post_content;
    ?>">
  </label>

  <label>Image
    <input type="file" id="image" name="image" ,
    value="<?php 
    echo $workouts->image;
    ?>">
  </label>


  <div class="grid-x grid-margin-x">
    <div class="large-6 cell">
      <a href="/workouts/index" class="alert button expanded">Cancel</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" value="Promjeni podatke"></input>
    </div>
  </div>
</form>
<?php echo $poruka; ?>