



<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    

    <!-- Login Form -->
    <form method="POST"
action="/index/autorizacija">
      <input type="text" id="email" class="fadeIn second" name="email" placeholder="login"  value="<?php echo $email ?>">
      <input type="text" id="lozinka" class="fadeIn third" name="lozinka" placeholder="password">
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>
    <?php echo $poruka; ?>
    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>